/* صور اللاعبين الرسمية — المفتاح "النادي|الاسم كما في meta/players"، القيمة مسار أساس بلا امتداد:
   <base>.webp = قصّة شفافة 800×1000 (البطاقة والملف)، <base>_s.webp = 240×300 (القوائم).
   كل نادٍ يُضاف بعد التحقق من الهوية (رقم القميص ↔ كشف الموقع + مطابقة الوجه). من لا مدخل له يبقى بالقميص. */
'use strict';

/* رقم نسخة الصور: ارفعه عند إعادة توليد أي قصّة حتى لا يبقى المتصفح على النسخة القديمة */
const PLAYER_PHOTOS_VER = '4';

const PLAYER_PHOTOS = {
  // الصليبخات (17)
  'SLB|صالح خميس': '/assets/players/slb/2',
  'SLB|علي الموسوي': '/assets/players/slb/4',
  'SLB|خالد الشهري': '/assets/players/slb/7',
  'SLB|نواف الشيباني': '/assets/players/slb/8',
  'SLB|عبدالمحسن الصليلي': '/assets/players/slb/10',
  'SLB|أحمد الفهد': '/assets/players/slb/13',
  'SLB|ياسر دشتي': '/assets/players/slb/14',
  'SLB|ويلفز دامسينا': '/assets/players/slb/20',
  'SLB|عبدالرحمن الشريفي': '/assets/players/slb/22',
  'SLB|ناصر الفيلكاوي': '/assets/players/slb/25',
  'SLB|لوكاس شالون': '/assets/players/slb/27',
  'SLB|عبدالله عيسى': '/assets/players/slb/36',
  'SLB|إيليلسون بيبي': '/assets/players/slb/44',
  'SLB|برونو دومنيغيس': '/assets/players/slb/55',
  'SLB|عبدالعزيز القطان': '/assets/players/slb/77',
  'SLB|عبدالله العوضي': '/assets/players/slb/88',
  'SLB|علي علاء الدين': '/assets/players/slb/93',
  // الساحل (22)
  'SAH|مشعل الرشيدي': '/assets/players/sah/1',
  'SAH|عمر العنزي': '/assets/players/sah/4',
  'SAH|عبدالرحمن الديحاني': '/assets/players/sah/5',
  'SAH|يوسف بادي': '/assets/players/sah/6',
  'SAH|محمد العلاطي': '/assets/players/sah/7',
  'SAH|أحمد غازي': '/assets/players/sah/8',
  'SAH|محمد العتيبي': '/assets/players/sah/11',
  'SAH|فيصل المكيمي': '/assets/players/sah/12',
  'SAH|ناصر القحطاني': '/assets/players/sah/14',
  'SAH|موريسيو': '/assets/players/sah/15',
  'SAH|جابر العجاجي': '/assets/players/sah/19',
  'SAH|فواز الدوسري': '/assets/players/sah/22',
  'SAH|لوكاس دي سوزا': '/assets/players/sah/23',
  'SAH|كليتون': '/assets/players/sah/27',
  'SAH|محمد الراشد': '/assets/players/sah/28',
  'SAH|ألن دي سوزا': '/assets/players/sah/29',
  'SAH|عبدالعزيز العنزي': '/assets/players/sah/30',
  'SAH|جواو': '/assets/players/sah/33',
  'SAH|بدر الزايد': '/assets/players/sah/44',
  'SAH|حمزه زياد': '/assets/players/sah/66',
  'SAH|راشد بن علي': '/assets/players/sah/77',
  'SAH|غازي العتيبي': '/assets/players/sah/87',
  // الشباب (16)
  'SHB|عبدالله جابر': '/assets/players/shb/1',
  'SHB|سعد العذاب': '/assets/players/shb/3',
  'SHB|يوسف محمد': '/assets/players/shb/4',
  'SHB|يعقوب الطراروه': '/assets/players/shb/10',
  'SHB|علي مصطفى': '/assets/players/shb/11',
  'SHB|محمد خليل': '/assets/players/shb/12',
  'SHB|سعد المطيري': '/assets/players/shb/18',
  'SHB|محمد القحطاني': '/assets/players/shb/20',
  'SHB|شاهين الخميس': '/assets/players/shb/22',
  'SHB|راشد فراج': '/assets/players/shb/23',
  'SHB|جيوفاني دي سيلفا': '/assets/players/shb/33',
  'SHB|عمر الحبيتر': '/assets/players/shb/37',
  'SHB|جاسم عتيق': '/assets/players/shb/45',
  'SHB|ماركوس مارتينلي': '/assets/players/shb/73',
  'SHB|ميشيل دي ليما': '/assets/players/shb/97',
  'SHB|ماثيوس توتو': '/assets/players/shb/99',
  // الفحيحيل (20)
  'FAH|علي فاضل': '/assets/players/fah/1',
  'FAH|حسين دشتي': '/assets/players/fah/2',
  'FAH|فهد سياف': '/assets/players/fah/3',
  'FAH|هاشم عدنان': '/assets/players/fah/4',
  'FAH|مشعل رومي': '/assets/players/fah/5',
  'FAH|محمد نعيم': '/assets/players/fah/6',
  'FAH|حمد الطويل': '/assets/players/fah/7',
  'FAH|عمر المطر': '/assets/players/fah/8',
  'FAH|رانجا شيفافيرو': '/assets/players/fah/9',
  'FAH|سلمان البوص': '/assets/players/fah/10',
  'FAH|الفين فورتيس': '/assets/players/fah/11',
  'FAH|شريدة الشريدة': '/assets/players/fah/15',
  'FAH|همام صبحي': '/assets/players/fah/17',
  'FAH|احمد النصر': '/assets/players/fah/24',
  'FAH|جاتوش بانوم': '/assets/players/fah/25',
  'FAH|احمد دشتي': '/assets/players/fah/26',
  'FAH|جاسم كرم': '/assets/players/fah/45',
  'FAH|عبدالعزيز ناجي': '/assets/players/fah/60',
  'FAH|محمد الفارسي': '/assets/players/fah/70',
  'FAH|خالد سليمان الشمري': '/assets/players/fah/77',
  // السالمية (25)
  'SAL|عبدالله الايوب': '/assets/players/sal/1',
  'SAL|عبدالله الجزاف': '/assets/players/sal/2',
  'SAL|عبد الرحمن الخضر': '/assets/players/sal/3',
  'SAL|شاهزود': '/assets/players/sal/4',
  'SAL|احمد بو مريوم': '/assets/players/sal/6',
  'SAL|محمود الأســود': '/assets/players/sal/7',
  'SAL|محمدالهويدي': '/assets/players/sal/8',
  'SAL|عبد الله يوسف': '/assets/players/sal/9',
  'SAL|فواز عايض': '/assets/players/sal/10',
  'SAL|نايف زويد': '/assets/players/sal/11',
  'SAL|احمد منصور': '/assets/players/sal/12',
  'SAL|احمد خورشيد': '/assets/players/sal/14',
  'SAL|مهدي دشتي': '/assets/players/sal/16',
  'SAL|يوسـف العنيـزان': '/assets/players/sal/17',
  'SAL|عبدالمحسن التركماني': '/assets/players/sal/18',
  'SAL|احمد عيدان': '/assets/players/sal/20',
  'SAL|عمر علي عمر': '/assets/players/sal/21',
  'SAL|يوسف الكندري': '/assets/players/sal/22',
  'SAL|عقيل الهزيم': '/assets/players/sal/23',
  'SAL|خالد العثمان': '/assets/players/sal/24',
  'SAL|مبارك الفنيني': '/assets/players/sal/26',
  'SAL|عيسى وليد': '/assets/players/sal/27',
  'SAL|تريسور': '/assets/players/sal/29',
  'SAL|عبدالرحمن الفضلي': '/assets/players/sal/35',
  'SAL|ديفيــد سامبيسا': '/assets/players/sal/77',
  // الكويت (20)
  'KUW|خالد الرشيدي': '/assets/players/kuw/1',
  'KUW|سامي الصانع': '/assets/players/kuw/2',
  'KUW|مشاري غنام': '/assets/players/kuw/3',
  'KUW|رضا هاني': '/assets/players/kuw/5',
  'KUW|ابراهيم كميل': '/assets/players/kuw/7',
  'KUW|احمد الظفيري': '/assets/players/kuw/8',
  'KUW|فيصل زايد': '/assets/players/kuw/9',
  'KUW|عموري': '/assets/players/kuw/10',
  'KUW|محمد دحام': '/assets/players/kuw/11',
  'KUW|محسن فلاح': '/assets/players/kuw/12',
  'KUW|يوسف ناصر': '/assets/players/kuw/20',
  'KUW|علي حسين': '/assets/players/kuw/21',
  'KUW|محمد فريح': '/assets/players/kuw/23',
  'KUW|محمد مرهون': '/assets/players/kuw/26',
  'KUW|مهند المحاميد': '/assets/players/kuw/28',
  'KUW|سعود الحوشان': '/assets/players/kuw/33',
  'KUW|زولا': '/assets/players/kuw/35',
  'KUW|سلمان العوضي': '/assets/players/kuw/39',
  'KUW|حسن حمدان': '/assets/players/kuw/44',
  'KUW|حمود السنعوسي': '/assets/players/kuw/72',
  // النصر (22)
  'NSR|ناصر خضر': '/assets/players/nsr/2',
  'NSR|علي عبدالله الظفيري': '/assets/players/nsr/3',
  'NSR|موريبا ديارا': '/assets/players/nsr/4',
  'NSR|نواف ثامر': '/assets/players/nsr/5',
  'NSR|عبدالرحمن كوكو': '/assets/players/nsr/6',
  'NSR|سيف الحشان': '/assets/players/nsr/7',
  'NSR|ايمن لقجع': '/assets/players/nsr/8',
  'NSR|فواز المبيلش': '/assets/players/nsr/9',
  'NSR|على حسن': '/assets/players/nsr/10',
  'NSR|يوسف ثامر': '/assets/players/nsr/11',
  'NSR|سلمان بورميه': '/assets/players/nsr/17',
  'NSR|حمود حزمي السهليي': '/assets/players/nsr/18',
  'NSR|هاشم نجيب': '/assets/players/nsr/19',
  'NSR|محمد عبدالهادي': '/assets/players/nsr/20',
  'NSR|محمد الحسينان': '/assets/players/nsr/22',
  'NSR|سيدي يعقوب': '/assets/players/nsr/24',
  'NSR|عبدالعزيز الشمري': '/assets/players/nsr/26',
  'NSR|خالد عجاجي': '/assets/players/nsr/33',
  'NSR|كريم سليم شاهين': '/assets/players/nsr/35',
  'NSR|عيد طلال رقبة': '/assets/players/nsr/40',
  'NSR|محمد حمد': '/assets/players/nsr/77',
  'NSR|حازم الحاج حسن': '/assets/players/nsr/99',
};
